using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace XSTH.Blueprint.Generators;

[Generator]
public class BlueprintSignalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all AdditionalFiles that end with .ui
        var uiFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".ui", StringComparison.OrdinalIgnoreCase));

        // Get the namespace from MSBuild properties (RootNamespace)
        var rootNamespace = context.AnalyzerConfigOptionsProvider
            .Select((options, _) =>
            {
                options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespaceValue);
                // Try to infer from path if not found, but we require a matching convention
                return string.IsNullOrWhiteSpace(rootNamespaceValue) ? "AppTemplate" : rootNamespaceValue;
            });

        // Combine the UI files with their specific options
        var fileAndOptions = uiFiles.Combine(context.AnalyzerConfigOptionsProvider);
        var inputs = fileAndOptions.Combine(rootNamespace!);

        context.RegisterSourceOutput(inputs, (spc, source) =>
        {
            var file = source.Left.Left;
            var optionsProvider = source.Left.Right;
            var rootNamespaceValue = source.Right;
            
            var options = optionsProvider.GlobalOptions;
            options.TryGetValue("build_property.ProjectDir", out var projectDir);
            options.TryGetValue("build_property.IntermediateOutputPath", out var intermediateOutputPath);
            
            var relativeDir = "";
            if (!string.IsNullOrEmpty(intermediateOutputPath))
            {
                var searchPath = intermediateOutputPath!.Replace('\\', '/').TrimEnd('/') + "/";
                var filePath = file.Path.Replace('\\', '/');
                
                var idx = filePath.IndexOf(searchPath, StringComparison.OrdinalIgnoreCase);
                if (idx >= 0)
                {
                    var relativePath = filePath.Substring(idx + searchPath.Length);
                    relativeDir = System.IO.Path.GetDirectoryName(relativePath) ?? "";
                }
            }
            
            GenerateCode(spc, file, rootNamespaceValue, relativeDir, intermediateOutputPath ?? "");
        });
    }

    private void GenerateCode(SourceProductionContext context, AdditionalText file, string rootNamespace, string relativeDir, string intermediateOutputPath)
    {
        var content = file.GetText(context.CancellationToken)?.ToString();
        if (string.IsNullOrWhiteSpace(content)) return;

        try
        {
            var doc = XDocument.Parse(content);
            var interfaceNode = doc.Element("interface");
            if (interfaceNode == null) return;

            // In GTK builder XML, the root object is typically our window/widget class
            var rootObject = interfaceNode.Element("object");
            if (rootObject == null) return;

            var windowId = rootObject.Attribute("id")?.Value;
            if (string.IsNullOrWhiteSpace(windowId)) return;

            // Extract all <signal> elements anywhere in the tree under this object
            var signals = rootObject.Descendants("signal")
                .Select(s => {
                    var parentObj = s.Ancestors("object").First();
                    return new
                    {
                        SignalName = s.Attribute("name")?.Value,
                        Handler = s.Attribute("handler")?.Value,
                        ObjectId = parentObj.Attribute("id")?.Value,
                        ObjectClass = parentObj.Attribute("class")?.Value
                    };
                })
                .Where(s => !string.IsNullOrEmpty(s.SignalName) && !string.IsNullOrEmpty(s.Handler) && !string.IsNullOrEmpty(s.ObjectId) && !string.IsNullOrEmpty(s.ObjectClass))
                .ToList();

            if (signals.Count == 0) return;

            // Dynamically evaluate sub-namespace based on MSBuild metadata passed directory
            var subNamespace = "";
            if (!string.IsNullOrEmpty(relativeDir))
            {
                var normalizedDir = relativeDir.Replace('\\', '/').Trim('/');
                if (!string.IsNullOrEmpty(normalizedDir))
                {
                    subNamespace = "." + string.Join(".", normalizedDir.Split('/'));
                }
            }
            var finalNamespace = $"{rootNamespace}{subNamespace}";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using Gtk;");
            sb.AppendLine();
            sb.AppendLine($"namespace {finalNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {windowId}");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Automatically wires up GTK signals defined in the Blueprint/UI file to the C# handlers.");
            sb.AppendLine("        /// Call this method after retrieving your widgets from the Gtk.Builder.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        protected override void ConfigureSignals(Gtk.Builder builder)");
            sb.AppendLine("        {");

            foreach (var sig in signals)
            {
                // Convert GTK signal name to C# Gir.Core Event Name (e.g. "clicked" -> "OnClicked")
                // Gir.Core maps signal "clicked" to event "OnClicked"
                var eventName = $"On{ToPascalCase(sig.SignalName)}";
                var typeName = MapToCSharpType(sig.ObjectClass!);

                // We assume builder.GetObject works because the user already loaded the UI
                sb.AppendLine($"            var {sig.ObjectId}_obj = builder.GetObject(\"{sig.ObjectId}\") as {typeName};");
                sb.AppendLine($"            if ({sig.ObjectId}_obj != null)");
                sb.AppendLine("            {");
                sb.AppendLine($"                {sig.ObjectId}_obj.{eventName} += {sig.Handler};");
                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{windowId}.Signals.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
        catch (Exception)
        {
            // Generator exceptions fail silently or can be logged as diagnostics
        }
    }

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        var parts = input.Split(new[] { '-', '_' }, StringSplitOptions.RemoveEmptyEntries);
        var result = new StringBuilder();
        foreach (var part in parts)
        {
            result.Append(char.ToUpper(part[0]));
            if (part.Length > 1)
            {
                result.Append(part.Substring(1).ToLower());
            }
        }
        return result.ToString();
    }

    private static string MapToCSharpType(string gtkClassName)
    {
        if (string.IsNullOrEmpty(gtkClassName)) return "Gtk.Widget";

        if (gtkClassName.StartsWith("Gtk", StringComparison.Ordinal)) return "Gtk." + gtkClassName.Substring(3);
        if (gtkClassName.StartsWith("Adw", StringComparison.Ordinal)) return "Adw." + gtkClassName.Substring(3);
        if (gtkClassName.StartsWith("Gio", StringComparison.Ordinal)) return "Gio." + gtkClassName.Substring(3);
        if (gtkClassName.StartsWith("Gdk", StringComparison.Ordinal)) return "Gdk." + gtkClassName.Substring(3);
        if (gtkClassName.StartsWith("GObject", StringComparison.Ordinal)) return "GObject." + gtkClassName.Substring(7);
        if (gtkClassName.StartsWith("GLib", StringComparison.Ordinal)) return "GLib." + gtkClassName.Substring(4);
        if (gtkClassName.StartsWith("Gsk", StringComparison.Ordinal)) return "Gsk." + gtkClassName.Substring(3);
        if (gtkClassName.StartsWith("Pango", StringComparison.Ordinal)) return "Pango." + gtkClassName.Substring(5);

        return gtkClassName; // Fallback for custom components
    }
}
